feat: make js-beautify optional, closes #49
ajv-validator/ajv-pack pull request #50
Opened 2020-11-26 03:43 UTC by proppy

2020-11-29 21:14 UTC, thomasw requested changes

2020-11-29 21:14 UTC, thomasw commented on lib/pack_validate.js
> +var beautify;
Default beautify to a function that returns the input unaltered so that you don't have to guard against it not being set elsewhere.

2020-11-29 21:14 UTC, thomasw commented on scripts/compile-dots.js
> +  , doT = require('dot');
As is, this script requires devDependencies and is not exposed via package.json's bin field. It's okay for this one to have a hard dependency on js-beautify.

2020-12-04 20:05 UTC, epoberezkin commented
@proppy  - thank you.

The latest version of Ajv (7-beta.9) includes the code to produce standalone code (and it doesn't use js-beautify - it is better to use directly, plus there are other options) - see docs/standalone.md in ajv.

I am planning to release the update to ajv-cli over the weekend that would use it.

v7 support for standalone code is stable, and it works with all recursive cases that are not supported by ajv-pack (the full JSON Schema test-suite passes). It also supports generating modules that export multiple validation functions - it reduces total code size if some parts are reused across multiple schemas.

So I suggest migrating to v7 - quite a few people migrated even though it's in beta :)

I would rather not merge this PR, I plan to mark this package as deprecated as soon as v7 becomes the main version - should be in a couple of weeks, but definitely this month - and archive in a few months after that.

2020-12-07 02:29 UTC, proppy commented
Thanks for the heads up, I will definitely give a try to Ajv 7 w the new schema packing capability!

> It also supports generating modules that export multiple validation functions - it reduces total code size if some parts are reused across multiple schemas.

I really excited about this, we have a big corpus of individual schema to pack https://github.com/actions-on-google/smart-home-schema and I was getting worried that this might end up in a lot of duplicated code if we were packing them individually.

2020-12-07 02:29 UTC, closed without merging

2020-12-07 06:37 UTC, epoberezkin commented
Let me know how it worked :)